/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidiserovich_cryptms_ZBarWrapper */

#ifndef _Included_com_davidiserovich_cryptms_ZBarWrapper
#define _Included_com_davidiserovich_cryptms_ZBarWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davidiserovich_cryptms_ZBarWrapper
 * Method:    decode
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_davidiserovich_cryptms_ZBarWrapper_decode
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
